name: clash-royale-daily

on:
  workflow_dispatch:
    # Uncomment to schedule
    #schedule:
    #- cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python Packages
        run: |
          cd notebooks
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt

      - name: Execute Python Workflows
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          API_TOKEN: ${{ secrets.CLASH_ROYALE_API_KEY }}
        run: |
          cd notebooks
          jupyter nbconvert --to notebook --execute 2_clash_royale_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_clash_royale_batch_inference_copy.ipynb

      - name: Create Custom HTML Dashboard
        run: |
          mkdir -p output
          echo '<!DOCTYPE html>' > output/dashboard.html
          echo '<html lang="en">' >> output/dashboard.html
          echo '<head>' >> output/dashboard.html
          echo '<meta charset="UTF-8">' >> output/dashboard.html
          echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">' >> output/dashboard.html
          echo '<title>Clash Royale Dashboard</title>' >> output/dashboard.html
          echo '</head>' >> output/dashboard.html
          echo '<body style="text-align: center; font-family: Arial, sans-serif; background-color: #f8f9fa; color: #333;">' >> output/dashboard.html
          echo '<h1>Clash Royale Predictions</h1>' >> output/dashboard.html
          echo '<p>Daily updated predictions for Clash Royale matches:</p>' >> output/dashboard.html
          echo '<img src="https://github.com/Grandediw/Clash-Royale-Project/raw/main/data/clash_royale_updated_predictions.png" alt="Clash Royale Predictions" style="max-width: 90%; height: auto; border: 1px solid #ddd; border-radius: 8px; padding: 10px;">' >> output/dashboard.html
          echo '</body>' >> output/dashboard.html
          echo '</html>' >> output/dashboard.html

      - name: Move Files to Root Directory
        run: |
          mv output/* .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output

      - name: GitHub Pages Publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clash Royale Dashboard published"
          commit_options: '--no-verify --signoff'
          repository: .
          status_options: '--untracked-files=no'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          push_options: '--force'
