name: clash-royale-daily

on:
  workflow_dispatch:
    #schedule:
    #- cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install python packages
        run: |
          cd notebooks
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          API_TOKEN: ${{ secrets.CLASH_ROYALE_API_KEY }}
        run: |
          cd notebooks
          jupyter nbconvert --to notebook --execute 2_clash_royale_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_clash_royale_batch_inference_copy.ipynb

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clash Royale Dashboard published"
          commit_options: '--no-verify --signoff'

          #file_pattern: 'docs/air-quality/assets/img/* docs/_includes/*'

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
