name: clash-royale--update-model-weekly

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 6 * * 1'  # Runs every Monday at 06:00 UTC

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python Packages
        run: |
          cd notebooks
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt

      - name: Execute Python Workflows
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          API_TOKEN: ${{ secrets.CLASH_ROYALE_API_KEY }}
        run: |
          cd notebooks
          jupyter nbconvert --to notebook --execute 3_clash_royale_training_pipeline.ipynb  # Added notebook execution
